### ISSUE TITLE
YouTube video auto paused when start playing in webpage player

### ISSUE THREAD

**Issue by javiavid** [PKM-er/media-extended#219]
I have tried creating a new vault, downloading BRAT and media extended, another link, I have reinstalled obsidian..
The problem is that every time you press play it only plays 1 frame and pauses again.
I get an error, Webview failed to load plugin in time.

In the video is the debug info of my vault.

https://github.com/PKM-er/media-extended/assets/7627504/eb8edef4-b9df-4ddc-9361-a98d965e9c9a

**Comment by aidenlx** [comment]
could you try beta 11 to see if it still happens? you can also try "show native controls" from more options menu to see if the problem presist

**Comment by javiavid** [comment]
The error still happens in the new version.

https://github.com/PKM-er/media-extended/assets/7627504/464475e1-ff2a-4d65-bd48-3d29f6b7e737

Maybe I don't remember it well, but I think that before when you ran open media it added the YouTube link to the note. Has this changed?

![image](https://github.com/PKM-er/media-extended/assets/7627504/dcfea9f1-0a7a-46e4-b34e-3f06d155f70b)

**Comment by javiavid** [comment]
I have also tried beta 12 and it is still the same.

**Comment by aidenlx** [comment]
[media-extended.zip](https://github.com/PKM-er/media-extended/files/14318232/media-extended.zip)
could you try this version?

**Comment by javiavid** [comment]
Beta 13 works! Thank you

**Comment by javiavid** [comment]
3.0.2-beta.0
The error has returned

**Comment by javiavid** [comment]
I upload a video in case it helps you to find the problem.
The videos look fine in the canvas and also in the login website, but not in the normal player.

https://github.com/PKM-er/media-extended/assets/7627504/a5ac8adb-4767-484f-a7a9-25a41ba288e5

**Comment by javiavid** [comment]
3.0.3 beta0 - ok
Thanks

**Comment by aidenlx** [comment]
The issue is not addressed in recent beta since I haven’t yet stably reproduce this issue. but I do have an assumption of the source of this issue.  will keep you informed if there are new attempts to fix this.

**Comment by javiavid** [comment]
It works fine for me right now, but it's true that it seems a bit intermittent.

I'm trying all the versions and there are times it works and other times it doesn't, even with the same versions.
I was trying to create a new vault, installing obsidian, firewall, antivirus... but I couldn't figure out what the problem was.

**Comment by FeralFlora** [comment]
> The issue is not addressed in recent beta since I haven’t yet stably reproduce this issue. but I do have an assumption of the source of this issue. will keep you informed if there are new attempts to fix this.

I'm still having the issue with beta0. When I press play, the playback stops after a millisecond, just enough to hear a sound, but then it stops.

**Comment by aidenlx** [comment]
could you check enabling the following flag in console solve this issue?
```js
localStorage.setItem('MX_DEV_DISABLE_WEBVIEW_TEMP_FRAG','1')
```

https://github.com/PKM-er/media-extended/assets/31102694/bca250da-763b-47b5-9b10-2fc366fbb0b9

**Comment by aidenlx** [comment]
From previous reports, it may become normal for some time. You can keep this flag on to see if this issue occur again. (note: this disable time range limits like `#t=5,10` that limit playback between 5s and 10s

**Comment by SchluppiBobbz** [comment]
Still doesn't work for me unfortunately.

**Comment by sebastien-k** [comment]
I also have this issue, even with the latest version (3.04).

**Comment by javiavid** [comment]
Hello, the problem continues in 3.04. I have tested the code in the console.
In 2.11.1 it works fine.

<img width="1024" alt="image" src="https://github.com/PKM-er/media-extended/assets/7627504/68babcd1-4f3f-4ee8-b3eb-b4f8d47b53d5">

**Comment by aidenlx** [comment]
could you check enabling the following flag in console solve this issue? (in 3.0.5-beta.0)

```
localStorage.setItem('MX_DEV_DISABLE_YTB_SKIP_AD','1')
```

this will disable auto ad skip, you'll have to use "Show native controls" in context menu to get access to "Skip Ad" button

**Comment by aidenlx** [comment]
@javiavid if you got time, you could DM me in discord to help me figure out the issue.
